spring.application.name=springSecurity
spring.security.user.name=admin
spring.security.user.password=admin123

# postgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/springSecurity
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=mySectretKey789321ljknlkhjbvnlkjn564fg65s413g21sd968g74f6d54gsdf6g4
# jwtSecret is a key to encode and decode the JWT token
# how jwtSecret works?
# when a user logs in, the server generates a JWT token using this secret key
# and sends it to the client. The client includes this token in the Authorization header
# of subsequent requests. The server then verifies the token using the same secret key
# to authenticate the user and authorize access to protected resources.
spring.app.jwtExpirationMs= 604800000
# jwtExpirationMs is the expiration time of the JWT token in milliseconds
# In this case, the token is set to expire in 15 minutes (900000 milliseconds)
# After this time, the user will need to log in again to obtain a new token.

logging.level.org.springframwork=DEBUG
loggin.level.org.hibernate.SQL=DEBUG
loggin.level.org.springframework.security=DEBUG
logging.level.com.shirzad.speringSecurity=DEBUG